server:
  port: 8080
  servlet:
    context-path: /paarr

management:
  endpoints:
    web:
      exposure:
        include: health,info,logfile
  endpoint:
    logfile:
      enabled: true
      external-file: /opt/onetn/apache-tomcat-10.1.18/logs/catalina.out
    health:
      show-details: always
      show-components: always

spring:
  freemarker:
    check-template-location: false
  datasource:
    driver-class-name: org.postgresql.Driver
    username: thalamz
    password: thalamzprod20252020
   
    #url: jdbc:postgresql://192.168.0.2:5432/postgres?currentSchema=paarr_dev
    url: jdbc:postgresql://thalamz-prod.cz624s8kkocj.ap-south-1.rds.amazonaws.com:5432/thalamz?currentSchema=staging_paarrever
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    open-in-view: false
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ALL

  mail:
   noreply:
      username: ravikumarranjith15@gmail.com
      password: knkwbbzfjtgqgvxn
      cc: 
   fest:
      username: ravikumarranjith15@gmail.com
      password: knkwbbzfjtgqgvxn
      cc: 
   errorReceipients: antony.j@amizhth.com
   supportReceipients: antony.j@amizhth.com
   properties:
    mail:
     smtp:
      auth: true
      starttls:
       enable: true
  http:
    multipart: 
      enabled: true
  sql:
    init:
      platform: postgres
      mode: always
      continue-on-error: false
  data:
     rest:
        detection-strategy: annotated

MaxFileSizeInMB: 5
MaxFileSizeInMB50: 50
OTPValidatityInSeconds: 120
  
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: info
    com.tnstartup.ecosystem.controller: debug
    


cloud:
   aws:
     credentials:
         access-key: AKIA5NLHMI6DF4AHHWPL
         secret-key: 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
     s3:
         bucket: paarr-dev-doc
     region:
         static: ap-south-1
     stack:
         auto: false