accesskey='AKIAS55SXV3AWQS45MQI'
secretkey='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'
region='AP_SOUTH_1'
profile.bucketname='paarr-devv-doc/profile'
trash.bucketname='paarr-devv-doc/trash'
category.bucketname='paarr-devv-doc/category'