accesskey='AKIA5NLHMI6DF4AHHWPL'
secretkey='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'
region='AP_SOUTH_1'
profile.bucketname='paarr-dev-doc/profile'
trash.bucketname='paarr-dev-doc/trash'
category.bucketname='paarr-dev-doc/category'