legalHeirSource={'TXP_DEPT'}
legalHeirUserName={'CM_RELIEFE'}
legalHeirPassword={'t$e)t$mR$(!$f'}
legalHeirAPIEndpoint='https://tnedistrict.cmsuat.co.in/stagging/getStatus'
districts={'Chengalpattu','Chennai','Kancheepuram','Tiruvallur','Coimbatore','Erode','Karur','Krishnagiri','Namakkal','The Nilgiris','Ranipet','Salem','Tiruchirappalli','Tirupattur','Tiruppur','Vellore','Ariyalur','Cuddalore','Dharmapuri','Dindigul','Kallakurichi','Kanniyakumari','Madurai','Mayiladuthurai','Nagapattinam','Perambulur','Pudukkottai','Ramanathapuram','Sivagangai','Tenkasi','Thanjavur','Theni','Thiruvarur','Thoothukudi','Tirunelveli','Tiruvannamalai','Villupuram','Virudhunagar'}
vahanmerchantid='CMARF_TN'
vahanmerchantsecret='CmArF_Tn@3418$'
vahanauthuri='https://delhigw.napix.gov.in/nic/parivahan/oauth2/token'
vahanclientkey='bfdd573881c47c38e312cfa359c26367'
vahanclientsecret='b284234ad129e0686d8b8f0b1a813ed0'
vahangetdetailsuri='https://delhigw.napix.gov.in/nic/parivahan/vahanws/service/getDetails'

